import { Link } from 'react-router-dom';
import { Card, Icon } from '../components/Ui';

const areas = [['/jobs', 'Jobs', 'Manage workshop jobs and related files.', 'construction'], ['/documents', 'Templates', 'Manage quotation, invoice, and delivery note templates.', 'description'], ['/companies', 'Companies', 'Maintain client company records.', 'business'], ['/engineers-buyers', 'Engineers & Buyers', 'Manage client contacts.', 'group']] as const;
const jobs = [['Turbine housing CNC re-bore', 'Apex Precision Eng.', '18 May 2026'], ['Flange assembly batch B-12', 'Vanguard Marine Ltd.', '17 May 2026'], ['Hydraulic ram seals replacement', 'Apex Precision Eng.', '17 May 2026'], ['Exhaust manifold milling', 'Solent Machining Co.', '16 May 2026'], ['Pump shaft repair', 'Vanguard Marine Ltd.', '15 May 2026'], ['Valve body machining', 'Apex Precision Eng.', '14 May 2026'], ['Gearbox casing inspection', 'Solent Machining Co.', '13 May 2026']];
const companyJobs = [['Apex Precision Eng.', 12], ['Vanguard Marine Ltd.', 8], ['Solent Machining Co.', 5]];
const documents = [['Quotation', 'QT-0001', 'Turbine housing CNC re-bore', '18 May 2026'], ['Invoice', 'INV-0001', 'Flange assembly batch B-12', '17 May 2026'], ['Delivery Note', 'DN-0001', 'Hydraulic ram seals replacement', '17 May 2026'], ['Quotation', 'QT-0002', 'Exhaust manifold milling', '16 May 2026'], ['Invoice', 'INV-0002', 'Pump shaft repair', '15 May 2026'], ['Delivery Note', 'DN-0002', 'Valve body machining', '14 May 2026'], ['Quotation', 'QT-0003', 'Gearbox casing inspection', '13 May 2026']];

export default function Dashboard() {
  return <div className="space-y-8">
    <div className="flex flex-col gap-4 md:flex-row md:items-center"><div><h1 className="text-3xl font-bold tracking-tight text-ink">Dashboard</h1><p className="mt-1 text-sm text-muted">Overview and quick access to workshop records.</p></div><div className="relative w-full md:ml-auto md:w-64"><label className="sr-only" htmlFor="global-search">Search</label><Icon className="pointer-events-none absolute left-3 top-3 text-muted">search</Icon><input id="global-search" className="field pl-10" placeholder="Search records" /></div></div>
    <div className="grid gap-4 sm:grid-cols-2 xl:grid-cols-4">{areas.map(([path, title, text, icon]) => <Link key={path} to={path} className="rounded-xl border border-outline/70 bg-surface p-5 shadow-card transition hover:border-primary-container hover:shadow-md"><span className="mb-5 flex h-10 w-10 items-center justify-center rounded-lg bg-surface-muted text-primary"><Icon>{icon}</Icon></span><h2 className="font-semibold text-ink">{title}</h2><p className="mt-1 text-sm leading-5 text-muted">{text}</p><span className="mt-5 flex items-center gap-1 text-sm font-semibold text-primary">Open <Icon className="text-[18px]">arrow_forward</Icon></span></Link>)}</div>
    <div className="grid gap-6 xl:grid-cols-2"><Card className="overflow-hidden p-0"><div className="flex items-center justify-between border-b border-outline/70 px-6 py-4"><h2 className="text-lg font-semibold">Recent jobs</h2><Link to="/jobs" className="text-sm font-semibold text-primary">View all</Link></div><div className="max-h-72 divide-y divide-outline/60 overflow-y-auto">{jobs.map(([name, company, date]) => <Link key={name} to="/jobs/1" className="flex items-center justify-between gap-4 px-6 py-4 transition hover:bg-surface-subtle"><div><p className="font-semibold text-ink">{name}</p><p className="mt-0.5 text-sm text-muted">{company}</p></div><time className="shrink-0 text-sm text-muted">{date}</time></Link>)}</div></Card>
      <Card><h2 className="text-lg font-semibold">Jobs by company</h2><p className="mt-1 text-sm text-muted">Current job records grouped by company.</p><div className="mt-5 grid gap-3 sm:grid-cols-3 xl:grid-cols-1">{companyJobs.map(([company, count]) => <div key={company} className="flex items-center justify-between gap-3 rounded-lg border border-outline/70 bg-surface-subtle/60 px-3 py-3"><span className="text-sm font-medium text-ink">{company}</span><span className="shrink-0 rounded-full px-2.5 py-1 text-sm font-semibold text-primary">{count} jobs</span></div>)}</div><Link to="/companies" className="mt-8 inline-flex items-center gap-1 text-sm font-semibold text-primary">View companies <Icon className="text-[18px]">arrow_forward</Icon></Link></Card></div>
    <Card className="overflow-hidden p-0"><div className="flex items-center justify-between border-b border-outline/70 px-6 py-4"><h2 className="text-lg font-semibold">Recently created documents</h2><Link to="/documents" className="text-sm font-semibold text-primary">Manage templates</Link></div><div className="max-h-72 divide-y divide-outline/60 overflow-y-auto">{documents.map(([type, reference, job, date]) => <Link key={reference} to="/jobs/1" className="flex flex-col gap-1 px-6 py-4 transition hover:bg-surface-subtle sm:flex-row sm:items-center sm:justify-between sm:gap-4"><div><p className="font-semibold text-ink">{type} <span className="font-normal text-muted">· {reference}</span></p><p className="mt-0.5 text-sm text-muted">{job}</p></div><time className="shrink-0 text-sm text-muted">{date}</time></Link>)}</div></Card>
  </div>;
}
