import { useState } from 'react';
import { Card, Icon, Modal, PageHeader, Select } from '../components/Ui';

const contacts = [['David Miller', 'Buyer', 'Apex Precision Eng.', '+44 7700 900001', 'david.miller@apex.example'], ['Marcus Chen', 'Engineer', 'Apex Precision Eng.', '+44 7700 900002', 'marcus.chen@apex.example'], ['Claire Adams', 'Buyer', 'Vanguard Marine Ltd.', '+44 7700 900003', 'claire.adams@vanguard.example']];

export default function EngineersBuyers() {
  const [isCreating, setIsCreating] = useState(false);
  return <div className="space-y-6"><PageHeader title="Engineers & buyers" description="Manage company contacts." action={<button className="primary-button" type="button" onClick={() => setIsCreating(true)}><Icon>add</Icon>New contact</button>} />
    {isCreating && <Modal title="Create contact" description="Add an engineer or buyer to an existing company." onClose={() => setIsCreating(false)}><form className="mt-6" onSubmit={(event) => { event.preventDefault(); setIsCreating(false); }}><div className="grid gap-5 md:grid-cols-2"><div><label className="label" htmlFor="contact-name">Name *</label><input id="contact-name" className="field" required /></div><div><label className="label" htmlFor="contact-type">Type *</label><Select id="contact-type" options={['Engineer', 'Buyer']} /></div><div><label className="label" htmlFor="contact-company">Company *</label><Select id="contact-company" options={['Apex Precision Eng.', 'Vanguard Marine Ltd.']} /></div><div><label className="label" htmlFor="contact-mobile">Mobile number</label><input id="contact-mobile" className="field" type="tel" /></div><div className="md:col-span-2"><label className="label" htmlFor="contact-email">Email *</label><input id="contact-email" className="field" required type="email" /></div></div><div className="mt-6 flex justify-end gap-3"><button className="secondary-button" type="button" onClick={() => setIsCreating(false)}>Cancel</button><button className="primary-button" type="submit">Create contact</button></div></form></Modal>}
    <div className="grid gap-3 md:grid-cols-2 xl:grid-cols-5"><input className="field xl:col-span-2" placeholder="Search name, company, mobile, or email" /><Select options={['All types', 'Engineers', 'Buyers']} /><Select options={['All companies', 'Apex Precision Eng.', 'Vanguard Marine Ltd.']} /><Select options={['Newest first', 'Name A-Z']} /></div><Card className="overflow-hidden p-0"><div className="overflow-x-auto"><table className="w-full min-w-[780px] text-left text-sm"><thead className="border-b border-outline/70 bg-surface-subtle text-muted"><tr><th className="px-6 py-3 font-semibold">Name</th><th className="px-6 py-3 font-semibold">Type</th><th className="px-6 py-3 font-semibold">Company</th><th className="px-6 py-3 font-semibold">Mobile</th><th className="px-6 py-3 font-semibold">Email</th><th className="px-6 py-3" /></tr></thead><tbody className="divide-y divide-outline/60">{contacts.map(([name, type, company, mobile, email]) => <tr key={email}><td className="px-6 py-4 font-semibold">{name}</td><td className="px-6 py-4 text-muted">{type}</td><td className="px-6 py-4 text-muted">{company}</td><td className="px-6 py-4 text-muted">{mobile}</td><td className="px-6 py-4 text-muted">{email}</td><td className="px-6 py-4 text-right"><button className="font-semibold text-primary">Edit</button></td></tr>)}</tbody></table></div><div className="flex items-center justify-between border-t border-outline/60 px-6 py-4 text-sm text-muted"><span>Showing 3 contacts</span><div className="flex gap-2"><button className="secondary-button h-8 px-3" type="button">Previous</button><button className="secondary-button h-8 px-3" type="button">Next</button></div></div></Card></div>;
}
